package com.xjx.javastudydemos.mybatisdemo1.mapper;


import com.xjx.javastudydemos.mybatisdemo1.po.PrizeItem;

public interface PrizeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_item
     *
     * @mbggenerated
     */
    int insert(PrizeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_item
     *
     * @mbggenerated
     */
    int insertSelective(PrizeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_item
     *
     * @mbggenerated
     */
    PrizeItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrizeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrizeItem record);
}