package com.xjx.javastudydemos.mybatisdemo1.mapper;


import com.xjx.javastudydemos.mybatisdemo1.po.PrizeDrawTemplate;

public interface PrizeDrawTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    int insert(PrizeDrawTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    int insertSelective(PrizeDrawTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    PrizeDrawTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PrizeDrawTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PrizeDrawTemplate record);
}