package com.xjx.javastudydemos.mybatisdemo1.po;

import java.io.Serializable;

public class PrizeDrawTemplate implements Serializable {
    /**
     * 主键，自动递增
     * 表字段 : prize_draw_template.id
     */
    private Long id;

    /**
     * 商铺id
     * 表字段 : prize_draw_template.shop_id
     */
    private String shopId;

    /**
     * 模板名称
     * 表字段 : prize_draw_template.name
     */
    private String name;

    /**
     * 抽奖样式id
     * 表字段 : prize_draw_template.style_id
     */
    private String styleId;

    /**
     * 抽奖样式名称
     * 表字段 : prize_draw_template.style_name
     */
    private String styleName;

    /**
     * 说明
     * 表字段 : prize_draw_template.description
     */
    private String description;

    /**
     * 奖品项最大数(不同抽奖样式的奖品项允许的最大数量可能不同）
     * 表字段 : prize_draw_template.prize_num_max
     */
    private Integer prizeNumMax;

    /**
     * 配送方式,1:无 , 2:门店自提,3:送货上门,4:门店自提+送货上门
     * 表字段 : prize_draw_template.delivery_type
     */
    private Integer deliveryType;

    /**
     * 1:有效，2：无效
     * 表字段 : prize_draw_template.status
     */
    private Short status;

    /**
     * 中奖总概率（整数）
     * 表字段 : prize_draw_template.win_rate
     */
    private Integer winRate;

    /**
     * 奖品门店自取的限制门店，存json格式，多个门店逗号隔开。eg:[{"id":"001","name":"南山店"},{"id":"002","name":"宝安店"}]
     * 表字段 : prize_draw_template.delivery_limit
     */
    private String deliveryLimit;

    /**
     * 奖品真实总数量
     * 表字段 : prize_draw_template.prize_real_num
     */
    private Integer prizeRealNum;

    /**
     * 奖品展示总数量
     * 表字段 : prize_draw_template.prize_show_num
     */
    private String prizeShowNum;

    /**
     * 创建时间（时间戳，单位：ms)
     * 表字段 : prize_draw_template.created_time
     */
    private Long createdTime;

    /**
     * 创建人（编号）
     * 表字段 : prize_draw_template.created_by
     */
    private Long createdBy;

    /**
     * 修改时间（时间戳，单位：ms)
     * 表字段 : prize_draw_template.updated_time
     */
    private Long updatedTime;

    /**
     * 修改人（编号）
     * 表字段 : prize_draw_template.updated_by
     */
    private Long updatedBy;

    /**
     * 是否删除（1：否；2：是）
     * 表字段 : prize_draw_template.ideleted
     */
    private Short ideleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    public PrizeDrawTemplate(Long id, String shopId, String name, String styleId, String styleName, String description, Integer prizeNumMax, Integer deliveryType, Short status, Integer winRate, String deliveryLimit, Integer prizeRealNum, String prizeShowNum, Long createdTime, Long createdBy, Long updatedTime, Long updatedBy, Short ideleted) {
        this.id = id;
        this.shopId = shopId;
        this.name = name;
        this.styleId = styleId;
        this.styleName = styleName;
        this.description = description;
        this.prizeNumMax = prizeNumMax;
        this.deliveryType = deliveryType;
        this.status = status;
        this.winRate = winRate;
        this.deliveryLimit = deliveryLimit;
        this.prizeRealNum = prizeRealNum;
        this.prizeShowNum = prizeShowNum;
        this.createdTime = createdTime;
        this.createdBy = createdBy;
        this.updatedTime = updatedTime;
        this.updatedBy = updatedBy;
        this.ideleted = ideleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    public PrizeDrawTemplate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.id
     *
     * @return the value of prize_draw_template.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.id
     *
     * @param id the value for prize_draw_template.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.shop_id
     *
     * @return the value of prize_draw_template.shop_id
     *
     * @mbggenerated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.shop_id
     *
     * @param shopId the value for prize_draw_template.shop_id
     *
     * @mbggenerated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.name
     *
     * @return the value of prize_draw_template.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.name
     *
     * @param name the value for prize_draw_template.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.style_id
     *
     * @return the value of prize_draw_template.style_id
     *
     * @mbggenerated
     */
    public String getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.style_id
     *
     * @param styleId the value for prize_draw_template.style_id
     *
     * @mbggenerated
     */
    public void setStyleId(String styleId) {
        this.styleId = styleId == null ? null : styleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.style_name
     *
     * @return the value of prize_draw_template.style_name
     *
     * @mbggenerated
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.style_name
     *
     * @param styleName the value for prize_draw_template.style_name
     *
     * @mbggenerated
     */
    public void setStyleName(String styleName) {
        this.styleName = styleName == null ? null : styleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.description
     *
     * @return the value of prize_draw_template.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.description
     *
     * @param description the value for prize_draw_template.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.prize_num_max
     *
     * @return the value of prize_draw_template.prize_num_max
     *
     * @mbggenerated
     */
    public Integer getPrizeNumMax() {
        return prizeNumMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.prize_num_max
     *
     * @param prizeNumMax the value for prize_draw_template.prize_num_max
     *
     * @mbggenerated
     */
    public void setPrizeNumMax(Integer prizeNumMax) {
        this.prizeNumMax = prizeNumMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.delivery_type
     *
     * @return the value of prize_draw_template.delivery_type
     *
     * @mbggenerated
     */
    public Integer getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.delivery_type
     *
     * @param deliveryType the value for prize_draw_template.delivery_type
     *
     * @mbggenerated
     */
    public void setDeliveryType(Integer deliveryType) {
        this.deliveryType = deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.status
     *
     * @return the value of prize_draw_template.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.status
     *
     * @param status the value for prize_draw_template.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.win_rate
     *
     * @return the value of prize_draw_template.win_rate
     *
     * @mbggenerated
     */
    public Integer getWinRate() {
        return winRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.win_rate
     *
     * @param winRate the value for prize_draw_template.win_rate
     *
     * @mbggenerated
     */
    public void setWinRate(Integer winRate) {
        this.winRate = winRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.delivery_limit
     *
     * @return the value of prize_draw_template.delivery_limit
     *
     * @mbggenerated
     */
    public String getDeliveryLimit() {
        return deliveryLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.delivery_limit
     *
     * @param deliveryLimit the value for prize_draw_template.delivery_limit
     *
     * @mbggenerated
     */
    public void setDeliveryLimit(String deliveryLimit) {
        this.deliveryLimit = deliveryLimit == null ? null : deliveryLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.prize_real_num
     *
     * @return the value of prize_draw_template.prize_real_num
     *
     * @mbggenerated
     */
    public Integer getPrizeRealNum() {
        return prizeRealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.prize_real_num
     *
     * @param prizeRealNum the value for prize_draw_template.prize_real_num
     *
     * @mbggenerated
     */
    public void setPrizeRealNum(Integer prizeRealNum) {
        this.prizeRealNum = prizeRealNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.prize_show_num
     *
     * @return the value of prize_draw_template.prize_show_num
     *
     * @mbggenerated
     */
    public String getPrizeShowNum() {
        return prizeShowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.prize_show_num
     *
     * @param prizeShowNum the value for prize_draw_template.prize_show_num
     *
     * @mbggenerated
     */
    public void setPrizeShowNum(String prizeShowNum) {
        this.prizeShowNum = prizeShowNum == null ? null : prizeShowNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.created_time
     *
     * @return the value of prize_draw_template.created_time
     *
     * @mbggenerated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.created_time
     *
     * @param createdTime the value for prize_draw_template.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.created_by
     *
     * @return the value of prize_draw_template.created_by
     *
     * @mbggenerated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.created_by
     *
     * @param createdBy the value for prize_draw_template.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.updated_time
     *
     * @return the value of prize_draw_template.updated_time
     *
     * @mbggenerated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.updated_time
     *
     * @param updatedTime the value for prize_draw_template.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.updated_by
     *
     * @return the value of prize_draw_template.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.updated_by
     *
     * @param updatedBy the value for prize_draw_template.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_draw_template.ideleted
     *
     * @return the value of prize_draw_template.ideleted
     *
     * @mbggenerated
     */
    public Short getIdeleted() {
        return ideleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_draw_template.ideleted
     *
     * @param ideleted the value for prize_draw_template.ideleted
     *
     * @mbggenerated
     */
    public void setIdeleted(Short ideleted) {
        this.ideleted = ideleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize_draw_template
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shopId=").append(shopId);
        sb.append(", name=").append(name);
        sb.append(", styleId=").append(styleId);
        sb.append(", styleName=").append(styleName);
        sb.append(", description=").append(description);
        sb.append(", prizeNumMax=").append(prizeNumMax);
        sb.append(", deliveryType=").append(deliveryType);
        sb.append(", status=").append(status);
        sb.append(", winRate=").append(winRate);
        sb.append(", deliveryLimit=").append(deliveryLimit);
        sb.append(", prizeRealNum=").append(prizeRealNum);
        sb.append(", prizeShowNum=").append(prizeShowNum);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", ideleted=").append(ideleted);
        sb.append("]");
        return sb.toString();
    }
}